{% set name = "pyroma" %}
{% set import = "pyroma" %}
{% set entrypoint = "pyroma" %}
{% set version = "4.0" %}
{% set sha256 = "b41ed0e080fb3aa9a7b8359d0ce7af39bc9b59cb9e7d696c6521f525257cc128" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - {{ entrypoint }} = {{ import }}:main

requirements:
  build:
    - python >=3.7
    - pip

  run:
    - docutils
    - pep517
    - pygments
    - python >=3.7
    - python-build
    - requests
    - setuptools
    - wheel

test:
  imports:
    - {{ import }}

  commands:
    - {{ entrypoint }} --help

about:
  home: https://github.com/regebro/pyroma/
  license: MIT
  license_file: LICENSE.txt
  summary: "Test your project's packaging friendliness"

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - jakirkham
