travis:
  secure:
    BINSTAR_TOKEN: f3q+qCgvuBF7NAVnIK0+GMtEhinKYA7WGvpndeaeCJnFV3gyAYIULQpXY5uvTax9eMz32NRAEEncFsKumnuI+vwv9S4YU5XPjQuF3tDTJbrF+QNEGEtrr/HrVw9SmwLdvGr6xk/04TxsWeEOhmoQh3QTs+/J9V+6RK52DC2TOt/nQmFGBJAKW89pCZeIVefg87tYrKkCZLVqFurpAkl/Lxdw4ylksuYtd33ypfD9fWj+N9Q3F+inaD4/20XFL1GQpT1v0qJ3QZY01KBjWW2vwBn2JjNZU3AN3Jxe1Nod7+l2XdqE0tMtaIlwyUm0K6mZLPu2P8qI0+VHrmOVvDMO72ctk2E+6AUo+ghmzDy7zULsrtJbU28BTC6sIrziqW78u5/8w0/Re8fzdds0DExl0lO5gUCxMpCGKyr3dBm1dZGgREDsj6O/jCeFUFZo9ZF2olJoZfdL7MzQpDvvDsJbR9Cmr6xUaUV2I9QYPq1Gzle1pSGz3mApCoXKZUB12MWxvuewoz3rhIRv3z1G5VHNAMuPYQbU9xTIz/gAaoFliji//C3NMJEjKe9XgygsdQFdH82NDxvl3T+gq/cqK1JwmfeqWWJrUew5KYeGWAhMLe7cszKhL+I4zrwbCJtPVPP0J5bSLSAgxigY8hfM2pfdtq2xLG4R3PFoiMvOPbUjOBY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
