travis:
  secure:
    BINSTAR_TOKEN: CAYqQG0b7QCu8TCaJMPZ1sJboJAL9FvfcUwwU0cbYn7yLTk5yeHuifBLEtkLQdqExf2roYl5Q7REZCaGvj5Ycx5brTnx8LoEc+li8ZLnKJUVono1WyIeE2mFHrXKA8ljJlixXQWr8trTTjlqUqQBQWnzjFSFHEUJXd5raulj9svTOVKpBJt2/lv765wR7lnOGw1XUvxt9TebifcBb6bFFqkKcsE42CVXwnZMjSoYtFYEByEGJTyIVvQtmcry3wT9q4tl/YV+ddok5PWQ+1IcUh4U0MoiiADzbcyH9RXnBTqsuc99t19kppTxQRiuk7pZ6qIL8iZ0hQ7HQ0fx5iX7M9hy7Q22nxJBjh4HyoafUSSR3tZx/6g1vn0d1WwuJ++4PPMRvdeEoTpPOan698npKVZSJxRjSU4dLnHy/iEDpBvnurZR4/Rxjy+diNgmsM5mIYXO09v+EGE32RWOoLB3Ogjjzwp0aG8RicYiuO362cZmFzDxMMipaQ8iIe2+rjVYYMVC4Zf7oJnavfeEyZ4PYA6B4LGrqrkz804hV5Xtz9BvmMv0Zsv9bi9Cz6csp4cYKRNjLLefCQMfdYhAEXhDedt6sjugK5qnzW67VNRw6TyE48LAFLH1IyQfAM6C++/lyXiNqm7YZS2kLWx6fbzz8lM7YOT7zQ5DoO74XAI+Efg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
