travis:
  secure:
    BINSTAR_TOKEN: YLsUmyebrWNhLgtVnzjbcWg8XLITWa9yLyUPOmtuAcGC5skBKcNXfNfAqwqAB48S9JKz9fGBVDQ/W20Zv95AiPbns/t/I1ErFSFZYrJYgMvPgVL2/BVHskpxIup8EdRDIWY3vxzRjGNFAGduMhTYztiG1iZO5z9f/+TsUy6hgaTJ/wWu8YclwycdGVGdaDOvn0tyVcgs5eg4ejrwoHkVEsayDVOSGK8hDWwiUQye7thXE1y4jaDsSyPQtrakcBChG6iD/7jpwIq/fWThfsft4Jd63+3lp3dyhB3Nng0bzF/OC105nAXBiGOwmx2UFAobQQCryFDpJ9E/9G32k0hkUKBqP0H+HSovdeDcKW0v8ygHRlnRcvPZZqVdPX9Z3F/37dd659dWWCc+hH5v8aZstiG7uwFSyM1DWWmX6+Cuq5v9yrAc8tGlbBz+FcPhvZ0Fv14MXl/G6lC8gsjqE/v4Z6xDdke7TGOQfa3jXuJHyoYu+x5IXkdbLzW+pC6JMdiYWb4UzjQtVHxhKorcmECMWgxw48+UcvFv3tRrFFKAKn4YJRtOdcJCmhrvd7LVJHoVdQsF/LlCgfRX2BDMHuTGlXFp1NY/+4jAxtl1J/zxobESl0qDqtF8nCq/G08UIv2MI4zOSZ3/5W4guzHn+HT4xTUTHeeq1PaXzQQwcW625QA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
